/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.upeu.farmacia.vista;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pe.edu.upeu.farmacia.config.Conexion;

/**
 *
 * @author HuBel
 */
public class Farmaciafrom extends javax.swing.JFrame {

    /**
     * Creates new form Farmaciafrorm
     */
    Conexion  conectar= new Conexion();
        Connection con;
    CallableStatement cst;
    ResultSet r;
    public Farmaciafrom() {
        initComponents();
        Calendar cal=Calendar.getInstance();
 String fecha=cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(cal.YEAR);
String hora=cal.get(cal.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+":"+cal.get(cal.SECOND); 
this.lblFecha.setText(fecha); 
this.lblHora.setText(hora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CerrarcesionMenuItem1 = new javax.swing.JMenuItem();
        SalirMenuItem5 = new javax.swing.JMenuItem();
        Mantenimiento = new javax.swing.JMenu();
        ManEmpleados = new javax.swing.JMenuItem();
        ManMedicamentos = new javax.swing.JMenuItem();
        ManClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MoFactura = new javax.swing.JMenuItem();
        MoBoleta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ReClientes = new javax.swing.JMenuItem();
        RepEmpleado = new javax.swing.JMenuItem();
        RepMedicamento = new javax.swing.JMenuItem();
        RepFactura = new javax.swing.JMenuItem();
        RepBoleta = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        lblFecha.setText("00/00/00");

        lblHora.setText("00/00/00");

        jLabel2.setText("Hora");

        jLabel4.setText("Fecha");

        jMenu1.setText("Sistema");

        CerrarcesionMenuItem1.setText("Cerrar cesion");
        CerrarcesionMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarcesionMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(CerrarcesionMenuItem1);

        SalirMenuItem5.setText("Salir");
        SalirMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(SalirMenuItem5);

        jMenuBar1.add(jMenu1);

        Mantenimiento.setText("Mantenimiento");

        ManEmpleados.setText("Empleados ");
        ManEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManEmpleadosActionPerformed(evt);
            }
        });
        Mantenimiento.add(ManEmpleados);

        ManMedicamentos.setText("Productos");
        ManMedicamentos.setActionCommand("");
        ManMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManMedicamentosActionPerformed(evt);
            }
        });
        Mantenimiento.add(ManMedicamentos);

        ManClientes.setText("Clintes");
        ManClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManClientesActionPerformed(evt);
            }
        });
        Mantenimiento.add(ManClientes);

        jMenuBar1.add(Mantenimiento);

        jMenu4.setText("Moviento");

        MoFactura.setText("Factura");
        MoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoFacturaActionPerformed(evt);
            }
        });
        jMenu4.add(MoFactura);

        MoBoleta.setText("Boleta");
        MoBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoBoletaActionPerformed(evt);
            }
        });
        jMenu4.add(MoBoleta);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        ReClientes.setText("Clientes");
        ReClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReClientesActionPerformed(evt);
            }
        });
        jMenu5.add(ReClientes);

        RepEmpleado.setText("Empleado");
        RepEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepEmpleadoActionPerformed(evt);
            }
        });
        jMenu5.add(RepEmpleado);

        RepMedicamento.setText("Medicamentos");
        RepMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepMedicamentoActionPerformed(evt);
            }
        });
        jMenu5.add(RepMedicamento);

        RepFactura.setText("Factura");
        RepFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepFacturaActionPerformed(evt);
            }
        });
        jMenu5.add(RepFactura);

        RepBoleta.setText("Boleta");
        RepBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepBoletaActionPerformed(evt);
            }
        });
        jMenu5.add(RepBoleta);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 241, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(lblHora)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblHora)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManEmpleadosActionPerformed
        // TODO add your handling code here:
        
          ConsultasEmpleados ce;
        try {
            ce = new ConsultasEmpleados();
            jDesktopPane2.add(ce);
            ce.setLocation(50, 5);
        ce.show();
        ce.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Farmaciafrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ManEmpleadosActionPerformed

    private void SalirMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMenuItem5ActionPerformed
        // TODO add your handling code here:
                                             
      int opcion=JOptionPane.showConfirmDialog(null,"Realmente desea Salir","confirmar",JOptionPane.YES_NO_OPTION);
if(opcion==JOptionPane.YES_NO_OPTION){
System.exit(0);
}
        
    
    
    }//GEN-LAST:event_SalirMenuItem5ActionPerformed

    private void CerrarcesionMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarcesionMenuItem1ActionPerformed
        // TODO add your handling code here:

  Sistema acs=new Sistema();
         acs.show(true);
         this.hide();
    }//GEN-LAST:event_CerrarcesionMenuItem1ActionPerformed

    private void ManClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManClientesActionPerformed
        // TODO add your handling code here:
      try{
        Cliente c =new Cliente();
        jDesktopPane2.add(c);
        c.show();
        c.setLocation(50, 5);
       }catch(Exception e){}  
        
    }//GEN-LAST:event_ManClientesActionPerformed

    private void ManMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManMedicamentosActionPerformed
        // TODO add your handling code here:
           

    }//GEN-LAST:event_ManMedicamentosActionPerformed

    private void ReClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReClientesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "conecion exitosa");
    }//GEN-LAST:event_ReClientesActionPerformed

    private void MoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoFacturaActionPerformed
        // TODO add your handling code here:
        try{
        Factura f=new Factura();
        jDesktopPane2.add(f);
       f.setLocation(50, 5); 
        f.show();
        f.setVisible(true);
       }catch(Exception e){}
    }//GEN-LAST:event_MoFacturaActionPerformed

    private void MoBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoBoletaActionPerformed
        // TODO add your handling code here:
        try{
        Boleta b=new Boleta();
        jDesktopPane2.add(b);
        b.setLocation(50, 5);
        b.show();
        b.setVisible(true);
        }catch (Exception e){JOptionPane.showMessageDialog(this,"error de ejecucion"+e.getMessage());
        }
    }//GEN-LAST:event_MoBoletaActionPerformed

    private void RepEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepEmpleadoActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "conecion exitosa");
    }//GEN-LAST:event_RepEmpleadoActionPerformed

    private void RepMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepMedicamentoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "conecion exitosa");
    }//GEN-LAST:event_RepMedicamentoActionPerformed

    private void RepFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepFacturaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "conecion exitosa");
    }//GEN-LAST:event_RepFacturaActionPerformed

    private void RepBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepBoletaActionPerformed

JOptionPane.showMessageDialog(this, "conecion exitosa");        
// TODO add your handling code here:
    }//GEN-LAST:event_RepBoletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Farmaciafrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Farmaciafrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Farmaciafrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Farmaciafrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Farmaciafrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarcesionMenuItem1;
    private javax.swing.JMenuItem ManClientes;
    private javax.swing.JMenuItem ManEmpleados;
    private javax.swing.JMenuItem ManMedicamentos;
    private javax.swing.JMenu Mantenimiento;
    private javax.swing.JMenuItem MoBoleta;
    private javax.swing.JMenuItem MoFactura;
    private javax.swing.JMenuItem ReClientes;
    private javax.swing.JMenuItem RepBoleta;
    private javax.swing.JMenuItem RepEmpleado;
    private javax.swing.JMenuItem RepFactura;
    private javax.swing.JMenuItem RepMedicamento;
    private javax.swing.JMenuItem SalirMenuItem5;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    // End of variables declaration//GEN-END:variables
}
